apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: svc1
        image: fsedano/k8stest:null
        ports:
        - containerPort: 80