load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])


py_library(
    name = "lib2_lib",
    srcs = 
        glob(["src/*.py"]) +  ["__init__.py"]
    ,
)
